name: CI Pipeline for Calculator

on: [push, pull_request]  # Runs on every push and pull request

permissions:
  contents: write  # Grant GitHub Actions permission to push commits

jobs:
  build:
    runs-on: windows-latest  # Use Windows instead of Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetches code from GitHub repo

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install  # Use install instead of ci on Windows

      - name: Run JavaScript Lint Check
        run: npx eslint script.js || echo "Lint warnings found"

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # Deploy only on main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_access_token: ${{ secrets.GH_PAT }}  # Use PAT instead of default token
          publish_dir: ./public  # Ensure this is the correct build directory
